import { useMemo, useState } from "react";

const whatsapp = "201008797774";
const offers = [
  { title: "فلتر 7 مراحل", price: "649 ر.س", text: "تنقية متعددة المراحل مع تركيب منزلي وفحص أولي.", tone: "from-cyan-500 to-teal-800" },
  { title: "فلتر جامبو", price: "899 ر.س", text: "حل قوي للعائلات مع تدفق مناسب وخدمة تركيب منظمة.", tone: "from-blue-600 to-indigo-900" },
  { title: "تغيير الشمعات", price: "149 ر.س", text: "تغيير الشمعات الأساسية مع مراجعة سريعة لحالة الفلتر.", tone: "from-amber-400 to-orange-700" },
  { title: "ممبرين + فحص شامل", price: "299 ر.س", text: "تغيير الممبرين وفحص الوصلات والخزان والتدفق.", tone: "from-emerald-500 to-teal-900" },
];

function wa(message: string) { window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); }

export default function PublicDemo() {
  const [sent, setSent] = useState(false);
  const order = useMemo(() => `PP-${Math.floor(100000 + Math.random() * 899999)}`, []);
  return <main dir="rtl" className="min-h-screen bg-[#f3fbfb] text-slate-900">
    <header className="sticky top-0 z-30 border-b border-teal-100/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4"><a href="#top" className="text-xl font-black text-teal-950">نقطة <span className="text-cyan-600">نقاء</span></a><nav className="hidden gap-6 text-sm font-bold text-slate-600 md:flex"><a href="#offers">العروض</a><a href="#services">الخدمات</a><a href="#why">لماذا نحن</a><a href="#contact">تواصل معنا</a></nav><button onClick={() => wa("أرغب في معرفة عروض نقطة نقاء") } className="rounded-full bg-teal-700 px-4 py-2 text-sm font-black text-white">واتساب</button></div></header>
    <section id="top" className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-16 md:grid-cols-[1.05fr_.95fr] md:py-24"><div><p className="mb-4 font-black text-cyan-700">خدمة منزلية في الرياض</p><h1 className="text-4xl font-black leading-tight text-teal-950 md:text-6xl">مياه أنقى تبدأ من <span className="text-cyan-600">اختيارك الصحيح</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">فلاتر مياه، شمعات، تركيب وصيانة بخدمة واضحة وسريعة، مع عروض تجريبية قابلة للتحديث.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => document.getElementById("offers")?.scrollIntoView({ behavior: "smooth" })} className="rounded-full bg-teal-800 px-6 py-3 font-black text-white">اطلب الآن</button><button onClick={() => wa("مرحبًا، أريد عرضًا مناسبًا لفلتر مياه") } className="rounded-full border-2 border-teal-700 px-6 py-3 font-black text-teal-800">تواصل عبر واتساب</button></div></div><div className="relative min-h-[340px] overflow-hidden rounded-[2rem] bg-gradient-to-br from-cyan-400 via-teal-700 to-slate-950 p-8 text-white shadow-xl"><div className="absolute -left-12 -top-12 h-56 w-56 rounded-full bg-white/20 blur-2xl"/><div className="relative flex h-full flex-col justify-end"><p className="text-sm font-bold text-cyan-100">نقطة نقاء</p><h2 className="mt-3 text-4xl font-black leading-tight">نركّبها لك،<br/>ونتابعها معك.</h2><p className="mt-4 max-w-sm leading-7 text-cyan-50">جودة، ضمان، وفنيون مختصون داخل الرياض.</p></div></div></section>
    <section id="offers" className="bg-white px-4 py-16"><div className="mx-auto max-w-6xl"><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p className="font-black text-cyan-700">أسعار تجريبية</p><h2 className="mt-2 text-3xl font-black text-teal-950">عروض مختارة لمنزلك</h2></div><p className="text-sm text-slate-500">قابلة للتحديث حسب المنتج والمقاس</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{offers.map(o => <article key={o.title} className="overflow-hidden rounded-3xl border border-teal-100 bg-[#f7fdfd]"><div className={`h-32 bg-gradient-to-br ${o.tone} p-5 text-white`}><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-black">عرض تجريبي</span><div className="mt-8 text-xl font-black">{o.title}</div></div><div className="p-5"><p className="min-h-20 text-sm leading-7 text-slate-600">{o.text}</p><div className="mt-4 text-2xl font-black text-teal-800">{o.price}</div><button onClick={() => wa(`أرغب في حجز عرض: ${o.title} بسعر ${o.price}`)} className="mt-4 w-full rounded-xl bg-teal-800 px-4 py-3 font-black text-white">احجز العرض</button></div></article>)}</div></div></section>
    <section id="services" className="mx-auto max-w-6xl px-4 py-16"><p className="font-black text-cyan-700">خدماتنا</p><h2 className="mt-2 text-3xl font-black text-teal-950">كل ما يحتاجه فلترك في مكان واحد</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["بيع وتركيب الفلاتر", "الصيانة والفحص", "تغيير الشمعات", "قطع الغيار والمستلزمات"].map(x => <div key={x} className="rounded-2xl bg-white p-6 font-black text-teal-900 shadow-sm ring-1 ring-teal-100">{x}<p className="mt-3 text-sm font-normal leading-6 text-slate-500">موعد منظم وخدمة منزلية داخل الرياض.</p></div>)}</div></section>
    <section id="why" className="bg-teal-950 px-4 py-16 text-white"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">لماذا نقطة نقاء؟</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{["جودة موثوقة", "تركيب احترافي", "سرعة في الاستجابة", "متابعة بعد الخدمة"].map(x => <div key={x} className="rounded-2xl bg-white/10 p-5 font-black">{x}</div>)}</div></div></section>
    <section id="contact" className="mx-auto max-w-6xl px-4 py-16"><div className="rounded-3xl bg-white p-8 text-center shadow-sm ring-1 ring-teal-100"><p className="font-black text-cyan-700">جاهز للطلب؟</p><h2 className="mt-2 text-3xl font-black text-teal-950">تواصل معنا الآن</h2><p className="mt-4 text-slate-600">الرياض · واتساب وهاتف: 01008797774</p><button onClick={() => { setSent(true); wa("أرغب في طلب خدمة من نقطة نقاء"); }} className="mt-6 rounded-full bg-amber-400 px-7 py-3 font-black text-teal-950">ابدأ طلبك عبر واتساب</button>{sent && <p className="mt-4 text-sm font-bold text-emerald-700">تم تجهيز طلب التواصل رقم {order}</p>}</div></section>
    <a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" className="fixed bottom-5 left-5 z-40 rounded-full bg-emerald-500 px-5 py-3 font-black text-white shadow-lg">واتساب</a>
  </main>;
}
